house: LIBRARIAN
pocket: go.bigboxco/products/great-road-mapper/docs/configurations.md
crate: crate.B160B0C0E0004B26
fields:
  - type: input
    label: class
    value: documentation
  - type: input
    label: kind
    value: guide